on:
  pull_request:
    paths:
      - '!**.md'
      - 'drupal/**'
      - '.github/workflows/drupal-image-tests.yml'
  push:
    branches: [ main ]
    paths:
      - '!**.md'
      - 'drupal/**'
      - '.github/workflows/drupal-image-tests.yml'
jobs:
  drupal-tests:
    name: Drupal image tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        working-directory: drupal
        run: make test
