on:
  pull_request:
    paths:
      - '!**.md'
      - 'openshift/drupal/**'
      - '.github/workflows/php-openshift.yml'
  push:
    branches: [ main ]
    paths:
      - '!**.md'
      - 'openshift/drupal/**'
      - '.github/workflows/php-openshift.yml'
jobs:
  php-openshift:
    name: OpenShift Drupal tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        working-directory: openshift/drupal
        run: make test-php
